apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongodb-svc
spec:
  ports:
  - port: 27017
  selector:
    app: open5gs-mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mongodb
spec:
  selector:
    matchLabels:
      app: open5gs-mongodb
  template:
    metadata:
      labels:
        app: open5gs-mongodb
    spec:
      containers:
      - image: free5gmano/nextepc-mongodb
        name: open5gs-mongodb
        ports:
        - containerPort: 27017
          name: mongodb
        volumeMounts:
        - name: mongodb-persistent-storage
          mountPath: /data/db
      volumes:
      - name: mongodb-persistent-storage
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-mongodb-pv-claim
# ---
# kind: PersistentVolume
# apiVersion: v1
# metadata:
#   name: {{ .Release.Name }}-mongodb-pv-volume
#   labels:
#     type: local
# spec:
#   capacity:
#     storage: 20Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: "/mnt/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-mongodb-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  # storageClassName: rook-cephfs
---
apiVersion: batch/v1
kind: Job
metadata:
  name: mongodb-sim-inject
spec:
  parallelism: 1    
  completions: 1    
  activeDeadlineSeconds: 1800 
  backoffLimit: 30   
  template:         
    metadata:
      name: mongodb-sim-inject
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: mongodb-sim-inject
        image: towards5gs/open5gs-dbctl
        command:
        - /bin/bash
        - -c
        - '/open5gs/open5gs-dbctl --db_uri=mongodb://open-mongodb-svc.open5gs.svc.cluster.local/open5gs add 208930000000001 465B5CE8B199B49FAA5F0A2EE238A6BC E8ED289DEBA952E4283B54E88E6183CA'
      restartPolicy: OnFailure    